name: Run Fillrate Script with .env

on:
  workflow_dispatch:  # allows manual run
  schedule:
    - cron: '0 14 * * MON'  # every Monday at 2pm UTC

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Load .env and run script
        run: |
          export $(cat .env | xargs) && python fillrate8.py
